export const getAllProducts = () => {
  return [
    {
      id: 'DS-001',
      slug: 'demon-slayer-1',
      name: "Demon Slayer: Kimetsu no Yaiba, Vol. 1",
      category: 'Best Seller',
      price: 50_000,
      stock: 25,
      imageUrl: '/assets/images/demon_slayer_1.jpg',
      description: `Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family! Learning to destroy demons won’t be easy, and Tanjiro barely knows where to start. The surprise appearance of another boy named Giyu, who seems to know what's going on, might provide some answers—but only if Tanjiro can stop Giyu from killing his sister first!`,
      genre: "Fantasy",
      author: "Koyoharu Gotouge",
      pages: '192 Pages',
      language: "Indonesia & Japanese",
      vol: '1'
    },
    {
      id: 'DS-002',
      slug: 'demon-slayer-2',
      name: "Demon Slayer: Kimetsu no Yaiba, Vol. 2",
      category: 'Popular',
      price: 50_000,
      stock: 15,
      imageUrl: '/assets/images/demon_slayer_2.jpg',
      description: `Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family! During final selection for the Demon Slayer Corps, Tanjiro faces a disfigured demon and uses the techniques taught by his master, Urokodaki! As Tanjiro begins to walk the path of the Demon Slayer, his search for the demon who murdered his family leads him to investigate the disappearances of young girls in a nearby town.
`,
      genre: "Fantasy",
      author: "Koyoharu Gotouge",
      pages: '192 Pages',
      language: "Indonesia & Japanese",
      vol: '2'
    },
    {
      id: 'DS-003',
      slug: 'demon-slayer-3',
      name: "Demon Slayer: Kimetsu no Yaiba, Vol. 3",
      category: 'Popular',
      price: 50_000,
      stock: 45,
      imageUrl: '/assets/images/demon_slayer_3.jpg',
      description: `Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family! Tanjiro and Nezuko cross paths with two powerful demons who fight with magical weapons. Even help from Tamayo and Yushiro may not be enough to defeat these demons who claim to belong to the Twelve Kizuki that directly serve Kibutsuji, the demon responsible for all of Tanjiro's woes! But if these demons can be defeated, what secrets can they reveal about Kibutsuji?`,
      genre: "Fantasy",
      author: "Koyoharu Gotouge",
      pages: '192 Pages',
      language: "Indonesia & Japanese",
      vol: '3'
    },
    {
      id: 'DS-004',
      slug: 'demon-slayer-4',
      name: "Demon Slayer: Kimetsu no Yaiba, Vol. 4",
      category: 'Best Seller',
      price: 50_000,
      stock: 45,
      imageUrl: '/assets/images/demon_slayer_4.jpg',
      description: `Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family! After a fierce battle with a demon inside a maddening house of ever-changing rooms, Tanjiro has a chance to find out about the fighter in the boar-head mask. Who is this passionate swordsman and what does he want? Later, a new mission has Tanjiro and his compatriots heading for Mt. Natagumo and a confrontation with a mysterious and horrifying threat…`,
      genre: "Fantasy",
      author: "Koyoharu Gotouge",
      pages: '192 Pages',
      language: "Indonesia & Japanese",
      vol: '4'
    },
    {
      id: 'DS-005',
      slug: 'demon-slayer-5',
      name: "Demon Slayer: Kimetsu no Yaiba, Vol. 5",
      category: 'Popular',
      price: 50_000,
      stock: 10,
      imageUrl: '/assets/images/demon_slayer_5.jpg',
      description: `Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family! At Mt. Natagumo, Tanjiro, Zenitsu and Inosuke battle a terrible family of spider demons. Taking on such powerful enemies demands all the skill and luck Tanjiro has as he and his companions fight to rescue Nezuko from the spiders' web. The battle is drawing in other Demon Slayers but not all of them will leave Mt. Natagumo alive—or in one piece!`,
      genre: "Fantasy",
      author: "Koyoharu Gotouge",
      pages: '192 Pages',
      language: "Indonesia & Japanese",
      vol: '5'
    },
    {
      id: 'DS-006',
      slug: 'demon-slayer-6',
      name: "Demon Slayer: Kimetsu no Yaiba, Vol. 6",
      category: 'Popular',
      price: 50_000,
      stock: 35,
      imageUrl: '/assets/images/demon_slayer_6.jpg',
      description: `Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family! The members of the Demon Slayer Corps are sworn to destroy demons wherever they find them—but the condition of Tanjiro’s sister, Nezuko, is a problem. What will the Hashira—the leaders of the Demon Slayer Corps—do about Tanjiro protecting his own demonic sister? Meanwhile, Kibutsuji assembles his own minions and intensifies his search for Tanjiro…`,
      genre: "Fantasy",
      author: "Koyoharu Gotouge",
      pages: '192 Pages',
      language: "Indonesia & Japanese",
      vol: '6'
    },
    {
      id: 'DS-007',
      slug: 'demon-slayer-7',
      name: "Demon Slayer: Kimetsu no Yaiba, Vol. 7",
      category: 'Best Seller',
      price: 50_000,
      stock: 20,
      imageUrl: '/assets/images/demon_slayer_7.jpg',
      description: `Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family! While under the care of the Demon Slayer Corps, Hashira, Shinobu, Tanjiro, Zenitsu, Inosuke and Nezuko have recovered. They have even learned a new and powerful technique—Total Concentration! They'll need this new power and all their skill on their next demon-hunting mission aboard the mysterious Infinity Train as it takes them into the dreams of demons!`,
      genre: "Fantasy",
      author: "Koyoharu Gotouge",
      pages: '192 Pages',
      language: "Indonesia & Japanese",
      vol: '7'
    },
    {
      id: 'DS-008',
      slug: 'demon-slayer-8',
      name: "Demon Slayer: Kimetsu no Yaiba, Vol. 8",
      category: 'Best Seller',
      price: 50_000,
      stock: 40,
      imageUrl: '/assets/images/demon_slayer_8.jpg',
      description: `Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family! After dealing with several demonic enemies aboard the Infinity Train, Tanjiro, Zenitsu and Inosuke must face the demon spirit of the train itself! Even if they can stop the demon train, the minions of Muzan Kibutsuji are still out there and Tanjiro must continue to improve his strength and skills. Learning the secret of the Hikonami Kagura and Flame Breathing will give him a powerful new advantage.`,
      genre: "Fantasy",
      author: "Koyoharu Gotouge",
      pages: '192 Pages',
      language: "Indonesia & Japanese",
      vol: '8'
    },

  ]
}